### PR TITLE
I just made some code more readable and added a VERY basic tutorial.

### PR DESCRIPTION
**Pull request by Edi-Gaming**
It would be nice to have a development branch

### CODE REVIEW

**Comment by InNoHurryToCode** [comment]
Granted your wish for a development branch.

**Comment by Edi-Gaming** [comment]
Oh sorry but thank you.

**Comment by themaoci** [comment]
anyway @Edi-Gaming good im forced to made it more readable because i will compress all files so it will be unreadable for normal ppl ;)

**Comment by Edi-Gaming** [comment]
the reason. I edited the commented padding because I was looking at this code in compressed because I'm lazy and I didn't see anything to improve. what I don't understand is: why this font it is hard to read because it is very thin on mobile it is almost unreadable I suggest some thing like console pro or good ol'arial I will try and see how it looks. also I am in eastern time so I am writing this at 2. sorry for any grammatical mistakes.

**Pull request merged**
